### ISSUE TITLE
problems with display function

### ISSUE THREAD

**Issue by bms1272** [yoelcortes/biosteam#1]
Using Jupyter labs I have had issues with displaying units and systems. Even when I copy example text directly from the website there is an error message even with basic units that work fine with the .show() function.
![biosteam unit diagram error](https://user-images.githubusercontent.com/57260701/68029332-5fd69f00-fc8d-11e9-8c98-ea5d338e830e.png)

**Comment by yoelcortes** [comment]
Hi, thanks for finding this bug. It is now fixed in biosteam==0.9.1.5. Just a heads up, Unit objects are abstract classes for defining a Unit subclass. You can use any of the predefined units (e.g. Mixer, Splitter, Flash, ect.) to simulate unit operations.
