### ISSUE TITLE
bst.[UnitName] vs bst.units.[UnitName]

### ISSUE THREAD

**Issue by yalinli2** [yoelcortes/biosteam#11]
**Description**
It appears that we can access biosteam native unit operations (e.g., Flash) by using either `bst.Flash` or `bst.units.Flash`, are there any differences and what is the preferred way?

Additionally, I can access more units in the dropdown menu when I hit tab in Spyder after `bst.units.` than after `bst.`, but not showing in the dropdown menu in `bst.` is not preventing me from calling these units, i.e., `bst.Centrifuge_LLE` works as well as `bst.units.Centrifuge_LLE` even if `Centrifuge_LLE` is only shown in the dropdown menu in `bst.units.`

I'm not sure whether the dropdown menu thing is a Sypder bug...

**Screenshots**
Note that the dropdown menu for `bst.` only contains `Flash` but not `Centrifuge_LLE`, and both of them appear in the dropdown menu for `bst.units`

<img width="590" alt="1" src="https://user-images.githubusercontent.com/49011373/72170808-290cbb80-3397-11ea-8a92-392cb403eb9f.png">

<img width="590" alt="2" src="https://user-images.githubusercontent.com/49011373/72170814-2c07ac00-3397-11ea-929d-6eff511634f6.png">

<img width="590" alt="3" src="https://user-images.githubusercontent.com/49011373/72170827-2f029c80-3397-11ea-86fc-6b55708029d0.png">

**Comment by yoelcortes** [comment]
biosteam. <Unit> and biosteam.units.<Unit> are the same. The unit operation resides in biosteam.units, but biosteam searches through all it's subfolders when you try to access something that is not in the main folder. The unit later appears in the biosteam.<tab> menu because biosteam saves it for faster future access

**Comment by yalinli2** [comment]
Ah got it, thanks!!!
