### ISSUE TITLE
Tutorial examples for Splitter and Centrifuge_LLE units

### ISSUE THREAD

**Issue by yalinli2** [yoelcortes/biosteam#12]
**Describe the bug**
I think there is a typo in the example for `Splitter`, and the `Centrifuge_LLE` example is not working.

**To reproduce**
 - Splitter
I think the split should be (0.99, 0.1) instead of (0.99, 0.01) to give the results shown in screenshot 1

- Centrifuge_LLE
An error would occur as in screenshot 2

**Screenshots**
 - Screenshot 1
![Splitter](https://user-images.githubusercontent.com/49011373/72213046-6ebba800-34ad-11ea-83eb-917ec312465d.png)

 - Screenshot 2
![Centrifuge_LLE](https://user-images.githubusercontent.com/49011373/72213055-a0347380-34ad-11ea-9166-f2f0bbb42f9a.png)

**Environment**
 - Python: v3.7.0
 - OS: macOS 10.15.2 
*you might want to change the iOS in the template to macOS, I think iOS is for iPhone, not Mac*
 - BioSTEAM: v1.0.7

**Comment by yoelcortes** [comment]
Coolio, I'll fix up the Splitter example. As for the Centrifuge_LLE, the LLE algorithm is still in development and many times the results are not good. Please use the SplitCentrifuge_LLE instead (works like a splitter, but for liquids).

Quick note: I'll be on leave until Jan 22. Feel free to keep posting, but I might not be relying until later jaja

**Comment by yalinli2** [comment]
Oh no problem, enjoy your time off!!! 😛
