### ISSUE TITLE
Mass Balance unit for one chemical

### ISSUE THREAD

**Issue by yalinli2** [yoelcortes/biosteam#15]
**Description**
I'm trying to use the `Mass Balance` unit, but ran into problem when trying to modify the [example](https://biosteam.readthedocs.io/en/latest/units/MassBalance.html) provided for two chemicals, Iet's assume I just want the mass balance for ethanol.

**To Reproduce**
Modified codes below:
``` python
from biosteam import System
from biosteam.units import Mixer, Splitter, StorageTank, Pump, Flash, MassBalance
from thermosteam import Chemicals, Stream, settings
chemicals = Chemicals(['Water', 'Ethanol'])
settings.set_thermo(chemicals)
# water = Stream('water',
#                 Water=40,
#                 units='lb/s',
#                 T=350, P=101325)
ethanol = Stream('ethanol',
                 Ethanol=190,
                 T=300, P=101325)
target = Stream('target', flow=50)
# T1 = StorageTank('T1')
T2 = StorageTank('T2')
# P1 = Pump('P1', P=101325)
P2 = Pump('P2', P=101325)
M1 = Mixer('M1', outs='s1')
S1 = Splitter('S1', outs=('s2', 's3'), split=0.5)
F1 = Flash('F1', outs=('s4', 's5'), V=0.5, P =101325)
# Connect units
# water-T1-P1
ethanol-T2-P2
[P2-0, S1-0]-M1-F1-1-S1

MB1 = MassBalance('MB1', streams=[0],
                  chemical_IDs=['Ethanol'],
                  outs=target,
                  ins=(ethanol, S1-0))
mixSys = System('mixSys',
                 recycle=S1-0,
                 network=(MB1, T2, P2, M1, F1, S1))
# Make diagram to view system
mixSys.diagram()
mixSys.simulate()
MB1.show()
```

**Screenshot**
<img width="593" alt="Error" src="https://user-images.githubusercontent.com/49011373/75486164-a2756300-5971-11ea-993e-f3112045f791.png">

**Environment**
OS: macOS 10.15.3
biosteam: 2.2.1
thermosteam: 0.2.13

Thanks!!!

**Comment by yoelcortes** [comment]
The bug is in this line:
```
target = Stream('target', flow=50)
```
If the flow argument is given, it should be an array with the same length as the number of chemicals defined (in this case 2). I updated thermosteam to raise an error if you give an invalid flow. Either way, it should work if you replace the line with:
```
target = Stream('target', Ethanol=50)
```

Thanks :)

**Comment by yalinli2** [comment]
Ah!!! Can't believe I made such a stupid error..... 😭 
Yep it works now, thanks!!!

**Comment by yoelcortes** [comment]
It's not a dumb error! And thanks for posting the issue. It helps to make BioSTEAM more robust ^_^

**Comment by yalinli2** [comment]
😆I can certainly be creative in creating errors hahaha
