### ISSUE TITLE
How to batch-create new unit classes through excel?

### ISSUE THREAD

**Issue by yoelcortes** [yoelcortes/biosteam#7]
I noticed some really cool codes the cornstover biorefinery used to batch-create units using the factories module of biosteam and an Excel spreadsheet:
<img width="652" alt="Batch-create units" src="https://user-images.githubusercontent.com/49011373/71772538-3565c400-2f12-11ea-879a-baf0fdfe327b.png">

Can you explain how this works? I couldn't really understand the raw codes in the factories module and additionally, I was baffled by the fact that/I wanted to know:
- Seems like not all units in the spreadsheet were used
- Only some units were created this way, was this intended to be a quick way for simple units?
- Is there anyway for me to check what units were created this way in the console?

Sorry I have a ton of questions... I tried to look at the tutorial but still couldn't figure these out. Let me know if the answers were somewhere in the tutorial , thanks!!!

_Originally posted by @yalinli2 in https://github.com/yoelcortes/biosteam/issues/6#issuecomment-570827119_

**Comment by yoelcortes** [comment]
Sure! I think an actual implementation is easier to explain. Imagine we have an excel file named "new_units" that looks like this:

Unit | Feedstock handling | Mixer-Sulfuric acid mixer
-- | -- | --
Item | System | Mixer
Basis | Flow rate | Flow rate
Units | kg/hr | kg/hr
Size | 94697.00 | 136260.00
Upper bound | FALSE | FALSE
CEPCI | 522 | 522
Cost (USD) | $13,329,690.00 | $6,000.00
Exponent | 0.6 | 0.5
Electricity   (kW) | 783.00 | 0.00
Installation   factor | 1.7 | 1
Number | FALSE | FALSE

We will add these units to the module.
```python
from biosteam.units.factories import xl2mod 
import sys

# If you have the excel file in the same folder and you are lazy to get the path
import os
path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'new_units.xlsx')

# This transfers all unit operations to the module.
# Basically the units were imported from the excel file. 
xl2mod(path, sys.modules[__name__])
```
Now we can start creating the units:
```python
from biosteam import *
Stream.species = Species('Water', 'Ethanol')
F1 = FeedstockHandling('F1')
M1 = SulfuricAcidMixer('M1')
```
Note that `F1` is an instance of `Static` and `M1` is an instance of `Mixer` . 
```python
>>> isinstance(F1, units.Static)
True
>>> isinstance(M1, units.Mixer)
True
```
When the name does not include a dash (e.g. "Feedstock handling"), you are telling BioSTEAM to create a subclass of `Static`. If you include the name of a Unit subclass followed by a dash, (e.g. "Mixer-Sulfuric acid mixer"), then the new unit operation will subclass from that (e.g. "Mixer").

This method of creating unit operations is the same as this (but much easier for many units):
```python
@cost('Flow rate', 'System',
      units='kg/hr', S=94697.00, ub=None, CE=522,
      cost=13329690, n=0.6, kW=783, BM=1.7, N=None)
class FeedstockHandling(units.Static): pass

# And similarly
@cost(...)
class SulfuricAcidMixer(Mixer): pass
```

**Comment by yoelcortes** [comment]
So to directly answer your other questions:
* Seems like not all units in the spreadsheet were used.
   - I should probably delete those....
* Only some units were created this way, was this intended to be a quick way for simple units?
   - Yeah, unit operations with complex run/design/cost methods should be completely hard coded for transparency.
* Is there anyway for me to check what units were created this way in the console?
   - The Unit subclasses are in the module, so when you import the module you could use `dir(module)`, for example:
   ```python
   >>> from biorefineries.cornstover import units
   >>> dir(units)
   ['AerobicDigestion',
    'AmmoniaAdditionTank',
   ...]
   ```
   - Best is to just open the excel file to have a look tho

**Comment by yalinli2** [comment]
Thanks for the clear explanation! Now I get it!

**Comment by yalinli2** [comment]
A random question: how did you add a paragraph of codes so neatly like:
<img width="628" alt="Codes" src="https://user-images.githubusercontent.com/49011373/71781307-b19fec00-2f92-11ea-907b-dcf5b7b1b55c.png">


And table like:
<img width="489" alt="Table" src="https://user-images.githubusercontent.com/49011373/71781279-700f4100-2f92-11ea-8b73-453a4e6033c4.png">

I can only use screenshots...
(Sorry this is not under an appropriate thread... Thanks!)

**Comment by yoelcortes** [comment]
No problem, its all markdown:
https://guides.github.com/features/mastering-markdown/

For the tables, its easier if you write it on excel, ctrl+c, then paste. When you preview it, it looks nice, jaja

**Comment by yalinli2** [comment]
(Thanks for the reply on formatting, most of them work like a charm, esp. for the table! But I couldn't get the ">>>" and syntax color as you did) .

Let's assume I used the Excel method to create a `FeedstockHandling` class as:

Unit | Feedstock handling
-- | --
Item | System
Basis | Flow rate
Units | kg/hr
Size | 94697.00
Upper bound | FALSE
CEPCI | 522
Cost (USD) | $13,329,690.00
Exponent | 0.6
Electricity   (kW) | 783.00
Installation   factor | 1.7
Number | FALSE

And I made a new unit U101 (assuming I had created a stream called cornstover):
```
U101 = units.FeedstockHandling('U101', ins=cornstover)
```
Results:
```
U101.simulate()
U101.results()

Feedstock handling        Units     U101
Power         Rate           kW      861
              Cost       USD/hr     49.3
Design        Flow rate   kg/hr 1.04e+05
Cost          System        USD 1.41e+07
Purchase cost               USD 1.41e+07
Utility cost             USD/hr     49.3
```
So I have both Purchase cost and Utility cost. In the cornstover biorefinery, you reset the purchase cost to 0 using:
```
U101.cost_items['System'].cost = 0
```
And this indeed can set purchase cost to 0 (since the only  cost_items is System):
```
U101 = units.FeedstockHandling('U101', ins=cornstover)
```
Results:
```
U101.simulate()
U101.results()

Feedstock handling        Units     U101
Power         Rate           kW      861
              Cost       USD/hr     49.3
Design        Flow rate   kg/hr 1.04e+05
Cost          System        USD        0
Purchase cost               USD        0
Utility cost             USD/hr     49.3
```

**My question is, can we do the same to the electricity? I.e., setting Utility cost to 0 in the code without changing the Excel spreadsheet.**

I tried to do the following:
```
U101._has_power_utility = False
U101._power_utility.rate = 0
U101._power_utility.cost = 0
```
The `_has_power_utility` function seemed to be doing nothing (to me, I'm sure it would do something somewhere).

The `_power_utility.rate` and `_power_utility.cost` can temporarily change Utility rate/cost to 0:
```
U101.results()

Feedstock handling        Units     U101
Power         Rate           kW        0
              Cost       USD/hr     49.3
Design        Flow rate   kg/hr 1.04e+05
Cost          System        USD        0
Purchase cost               USD        0
Utility cost             USD/hr     49.3
```
But they would be overwritten upon simulation:
```
U101.simulate()
U101.results()

Feedstock handling        Units     U101
Power         Rate           kW      861
              Cost       USD/hr     49.3
Design        Flow rate   kg/hr 1.04e+05
Cost          System        USD        0
Purchase cost               USD        0
Utility cost             USD/hr     49.3
```

A side note, in the Humbird report, the electricity for Area 100 is also 0. They calculated it out, then added an operating cost credit back, you probably have considered this.

Thanks!!!

**Comment by yoelcortes** [comment]
* GitHub markdown:
   I add the ">>> " simply by adding it myself at the start of each line, lol. The syntax coloring is done by using ```python.
* I think you might have missed it; so make sure to checkout the API and tutorial in the documentation:
   - API: https://biosteam.readthedocs.io/en/latest/units/decorators.html
   - Tutorial: https://biosteam.readthedocs.io/en/latest/tutorial/Unit%20decorators.html
* Use the `kW`attribute of a CostItem object to change electricity rate. For example:
   ```python
   # Note: If no upper bound for size, ub should be False
   #       not None, as in my previous example.
   @cost('Flow rate', 'System',
          units='kg/hr', S=94697.00, ub=False, CE=522,
          cost=13329690, n=0.6, kW=783, BM=1.7, N=None)
   class FeedstockHandling(units.Static): pass
   FeedstockHandling.cost_items['System']
   ```
   ```python
   >>> system_cost_item = FeedstockHandling.cost_items['System']
   >>> system_cost_item.kW = 0
   >>> system_cost_item
   CostItem: Flow rate (kg/hr)
   S     9.47e+04
   ub    0
   CE    522
   cost  1.33e+07
   n     0.6
   kW    0
   BM    1.7
   ```

**Comment by yalinli2** [comment]
Ah I didn't realize I can just set it using:
```
FeedstockHandling.cost_items['System'].kW=0
```
and I didn't grasp the flexibility of the `@cost` decorator, apparently it can do much more than I thought, thanks!!!

**Comment by yalinli2** [comment]
BTW I'm good with closing this issue, but I'm not the author so can't do it 😛
