### ISSUE TITLE
Clarification on using find function

### ISSUE THREAD

**Issue by yalinli2** [yoelcortes/biosteam#8]
I really like the `find` function in biosteam, but only want to ask something related to its usage (as instructed in the [tutorial on managing flowsheets](https://biosteam.readthedocs.io/en/latest/tutorial/Managing%20flowsheets.html)):

Let's assume I create a very simple stream in biosteam and try to `find` it:
`import biosteam as bst`
`species = bst.Species('Water', 'Ethanol')`
`bst.Stream.species = species`
`s0 = bst.Stream('s0', Water=1, Ethanol=1)`

When I try to use `find`, I can do:
`lost_stream = bst.find('s0')`

But I cannot use:
`lost_stream = bst.find.stream('s0')`

which will trigger an error:
<img width="463" alt="Error" src="https://user-images.githubusercontent.com/49011373/71781177-502b4d80-2f91-11ea-8e60-78a9982e0f7d.png">

Instead, I should use:
`lost_stream = bst.find.stream.s0`

Can you explain on the difference between `find` and `stream` and why this is the case?

Thanks!!!

**Comment by yoelcortes** [comment]
Sure thing, `find` is a MainFlowsheet object. You can call it and it will look for the object in the registers (i.e., the stream, unit, and system attributes). So `bst.find('s0')` is actually slower than `bst.find.stream.s0`. In other words, the stream/unit/system registers are components of the flowsheet.

Note that you could also use `getattr(bst.find.stream, ID)`, wherer `ID` is a string denoting the name of the stream.

**Comment by yalinli2** [comment]
Makes sense, thanks!!!
