### ISSUE TITLE
bst.Junction failing to copy flow information

### ISSUE THREAD

**Issue by yalinli2** [yoelcortes/biosteam#9]
**Describe the bug**
I noticed that under certain conditions, the `Junction` unit may fail to copy the upstream flow information into downstream flow, but I have not figure out what might be the case.

**To reproduce**
This can be seen in the cornstover system in biorefineries package.  I'll use M601 as an example. Note that in the original code, no ID was assigned so the default ID (U1) was used, there are several other instances like this, I'll compile them and submit another issue under Bioindustrial-Park.

```
import biosteam as bst
from biorefineries.cornstover import system
M601 = bst.find.unit.U1 
M601
# Note that d56 and d57 are empty streams, re-simulate won't fix it
(Screenshot #1)

M601.diagram(radius=1)
# Note that d56 and d57 are rejected_water_and_blowdown and evaporation_and_blowdown, 
# and they are not empty
(Screenshot #2)

bst.find.stream.rejected_water_and_blowdown
(Screenshot #3)

bst.find.stream.evaporation_and_blowdown
(Screenshot #4)

```

**Screenshots**
#1: M601_flow
<img width="569" alt="M601_flow" src="https://user-images.githubusercontent.com/49011373/72123359-9f250a00-3326-11ea-9a3d-2d7443a306a6.png">

#2: M601_diagram
![M601_diagram](https://user-images.githubusercontent.com/49011373/72123457-ef03d100-3326-11ea-8408-afe39cb9beb7.png)

#3: rejected_water_and_blowdown
<img width="569" alt="rejected_water_and_blowndown" src="https://user-images.githubusercontent.com/49011373/72123516-24102380-3327-11ea-8c3d-45d12358fd4e.png">

#4: evaporation_and_blowdown
<img width="569" alt="evaporation_and_blowndown" src="https://user-images.githubusercontent.com/49011373/72123503-19ee2500-3327-11ea-9cf8-05be3009d00a.png">

**Environment**
 - Python: v3.7.1
 - OS: iOS Catalina
 - BioSTEAM: v1.0.6
- biorefineries: v0.1.1

**Additional context**
Unlike Stream and Unit, which have name that we can easily using `find` function to locate, Junction does not have IDs and so far I can only use `import` to get the Junction unit I want. Is it possible to find them using `find` function?

**Comment by yoelcortes** [comment]
Thanks for catching this! This is definitely a bug. It should be fixed tomorrow. I'll also change the Junction class to have an ID (just like every other unit), so it can be easier to find. 

I just added the M602 ID to the unit in the biorefineries, I'll wait for your next post on the missing IDs before I update the biorefineries. :)

**Comment by yoelcortes** [comment]
Ok, bug is fixed in biosteam v1.0.7. I am closing this issue.

**Comment by yalinli2** [comment]
I'm not sure if the problem has been fixed, it's still not working on my end, I've checked that I have the v1.0.7.

Even example given in tutorial is not working

```python
from biosteam import *
>>> species = Species('Water')
>>> species.Sugar = compounds.Substance('Sugar')
>>> Stream.species = species
>>> s1 = Stream('s1', Water=20)
>>> Stream.species = Species('Water', 'Ethanol')
>>> s2 = Stream('s2') # Note that s2 and s1 have different Species objects
>>> J1 = units.Junction('J1', s1, s2)
>>> J1.simulate()
>>> J1.show()
```
Here's what I got:
![Junction](https://user-images.githubusercontent.com/49011373/72212898-5ea2c900-34ab-11ea-89da-3814f67ebd44.png)

Can you take another look and if that's the case on your end as well? Thanks!

**Comment by yoelcortes** [comment]
Ahh, I introduced another bug with the last update which made it fail in very particular scenarios. Could you make sure if biosteam==1.0.8 works for you? Thanks!

**Comment by yalinli2** [comment]
Yep it's working!!! 🎉 

Though when I tried to update `biosteam`, I was kindly reminded that `biorefineries` needed v1.0.7. I ignored it, and gladly found that `biorefineries` was still working after the update. 😉 

<img width="613" alt="biorefineries_requirements" src="https://user-images.githubusercontent.com/49011373/72532190-922d7c80-3838-11ea-8968-85872999e9ea.png">
